version: "3.3"
services:
  {{PROJECT_NAME_KEBAPCASE}}-db:
    container_name: {{PROJECT_NAME_KEBAPCASE}}-mysql-db
    image: mysql:5.7
    restart: always
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: "{{PROJECT_NAME_LOWERCASE}}_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - vol-{{PROJECT_NAME_KEBAPCASE}}-db:/var/lib/mysql
volumes:
  vol-{{PROJECT_NAME_KEBAPCASE}}-db:
